Update to show branch in meld path
Updated so that the branch name is in the meld path. Additionally, updated to make the cleanup easier since everything is in one directory.

diff --git a/mdiff b/mdiff
--- a/mdiff
+++ b/mdiff
@@ -1,43 +1,46 @@
 #!/bin/bash
 # Copyright (c) 2011, Terry Meacham <terry.t.meacham@gmail.com>
-# Copyright (c) 2011, Doug Goldstein <cardoe@cardoe.com>
+# Copyright (c) 2011-2013, Doug Goldstein <cardoe@cardoe.com>
 #
 # Based on svdiff script by Terry Meacham
 #
 # Released under the BSD 2-clause license
 
 if [[ $# -ne 2 ]]; then
-	echo "usage: $0 [svnpath to trunk] [svnpath to branch]"
-	exit 1;
+    echo "usage: $0 [svnpath to trunk] [svnpath to branch]"
+    exit 1;
 fi
 
-root=$(mktemp --directory --tmpdir=/var/tmp)
-trunk=$(mktemp --directory --tmpdir=/var/tmp)
-trunk_used=no
+base_dir=$(mktemp --directory --tmpdir=/var/tmp)
+review_stub=$(basename $2)
+review_stub=$(echo ${review_stub} | sed -e 's/@/_/')
+trunk_stub=$(basename $1)
+trunk_stub=$(echo ${trunk_stub} | sed -e 's/@/_/')
+review="${base_dir}/${review_stub}"
+trunk="${base_dir}/${trunk_stub}"
 
 # Removes what was previously in the review directory
-rm -rf $root
+rm -rf ${base_dir}
 
 # Checks out the branch to review
-echo "Checking out the review branch..."
-svn export --force --ignore-externals $2 $root > /dev/null
+echo "Checking out $(basename $2) for review..."
+svn export --force --ignore-externals $2 ${review} > /dev/null
+if [ $? -ne 0 ]; then
+    echo "Failed to checkout $2 to ${review}"
+    exit 1
+fi
 echo "Done!"
 
-# See if the path to trunk is a URL
-echo $1 | grep -c '://' > /dev/null
-if [[ $? -eq 0 ]]; then
-	echo "Checking out trunk..."
-	svn export --force --ignore-externals $1 $trunk > /dev/null
-	trunk_used=yes
-	echo "Done!"
+echo "Checking out $(basename $1)..."
+svn export --force --ignore-externals $1 ${trunk} > /dev/null
+if [ $? -ne 0 ]; then
+    echo "Failed to checkout $2 to ${trunk}"
+    exit 1
 fi
+echo "Done!"
 
-if [[ ${trunk_used} = "yes" ]]; then
-	meld "${trunk}" "${root}"
-	rm -rf "${trunk}"
-else
-	meld "$1" "${root}"
-fi
+meld "${trunk}" "${review}"
 
-rm -rf "${root}"
+rm -rf "${base_dir}"
 echo "Cleaned up"
+
